- name: ensure apache is at the latest version
  apt: name=apache2 state=latest
  tags: installation

- name: write the apache2 ports.conf config file
  template: src=practice-6/templates/ports.conf.j2 dest=/etc/apache2/ports.conf
  notify: restart apache
  tags: configuration

- name: write a basic index.html file
  template:
    src: practice-6/templates/index.html.j2
    dest: /var/www/html/index.html
  notify:
  - restart apache
  tags: configuration

- name: ensure apache is running
  service:
    name: apache2
    state: started