- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world!"
  tasks:
  - import_tasks: practice-4/tasks/apache2_install.yml

  handlers:
  - import_tasks: practice-4/handlers/main.yml